using System;

public static class Species {
	public const int BULBASAUR = 1;
	public const int IVYSAUR = 2;
	public const int VENUSAUR = 3;
	public const int CHARMANDER = 4;
	public const int CHARMELEON = 5;
	public const int CHARIZARD = 6;
	public const int SQUIRTLE = 7;
	public const int WARTORTLE = 8;
	public const int BLASTOISE = 9;
	public const int CATERPIE = 10;
	public const int METAPOD = 11;
	public const int BUTTERFREE = 12;
	public const int WEEDLE = 13;
	public const int KAKUNA = 14;
	public const int BEEDRILL = 15;
	public const int PIDGEY = 16;
	public const int PIDGEOTTO = 17;
	public const int PIDGEOT = 18;
	public const int RATTATA = 19;
	public const int RATICATE = 20;
	public const int SPEAROW = 21;
	public const int FEAROW = 22;
	public const int EKANS = 23;
	public const int ARBOK = 24;
	public const int PIKACHU = 25;
	public const int RAICHU = 26;
	public const int SANDSHREW = 27;
	public const int SANDSLASH = 28;
	public const int NIDORANfE = 29;
	public const int NIDORINA = 30;
	public const int NIDOQUEEN = 31;
	public const int NIDORANmA = 32;
	public const int NIDORINO = 33;
	public const int NIDOKING = 34;
	public const int CLEFAIRY = 35;
	public const int CLEFABLE = 36;
	public const int VULPIX = 37;
	public const int NINETALES = 38;
	public const int JIGGLYPUFF = 39;
	public const int WIGGLYTUFF = 40;
	public const int ZUBAT = 41;
	public const int GOLBAT = 42;
	public const int ODDISH = 43;
	public const int GLOOM = 44;
	public const int VILEPLUME = 45;
	public const int PARAS = 46;
	public const int PARASECT = 47;
	public const int VENONAT = 48;
	public const int VENOMOTH = 49;
	public const int DIGLETT = 50;
	public const int DUGTRIO = 51;
	public const int MEOWTH = 52;
	public const int PERSIAN = 53;
	public const int PSYDUCK = 54;
	public const int GOLDUCK = 55;
	public const int MANKEY = 56;
	public const int PRIMEAPE = 57;
	public const int GROWLITHE = 58;
	public const int ARCANINE = 59;
	public const int POLIWAG = 60;
	public const int POLIWHIRL = 61;
	public const int POLIWRATH = 62;
	public const int ABRA = 63;
	public const int KADABRA = 64;
	public const int ALAKAZAM = 65;
	public const int MACHOP = 66;
	public const int MACHOKE = 67;
	public const int MACHAMP = 68;
	public const int BELLSPROUT = 69;
	public const int WEEPINBELL = 70;
	public const int VICTREEBEL = 71;
	public const int TENTACOOL = 72;
	public const int TENTACRUEL = 73;
	public const int GEODUDE = 74;
	public const int GRAVELER = 75;
	public const int GOLEM = 76;
	public const int PONYTA = 77;
	public const int RAPIDASH = 78;
	public const int SLOWPOKE = 79;
	public const int SLOWBRO = 80;
	public const int MAGNEMITE = 81;
	public const int MAGNETON = 82;
	public const int FARFETCHD = 83;
	public const int DODUO = 84;
	public const int DODRIO = 85;
	public const int SEEL = 86;
	public const int DEWGONG = 87;
	public const int GRIMER = 88;
	public const int MUK = 89;
	public const int SHELLDER = 90;
	public const int CLOYSTER = 91;
	public const int GASTLY = 92;
	public const int HAUNTER = 93;
	public const int GENGAR = 94;
	public const int ONIX = 95;
	public const int DROWZEE = 96;
	public const int HYPNO = 97;
	public const int KRABBY = 98;
	public const int KINGLER = 99;
	public const int VOLTORB = 100;
	public const int ELECTRODE = 101;
	public const int EXEGGCUTE = 102;
	public const int EXEGGUTOR = 103;
	public const int CUBONE = 104;
	public const int MAROWAK = 105;
	public const int HITMONLEE = 106;
	public const int HITMONCHAN = 107;
	public const int LICKITUNG = 108;
	public const int KOFFING = 109;
	public const int WEEZING = 110;
	public const int RHYHORN = 111;
	public const int RHYDON = 112;
	public const int CHANSEY = 113;
	public const int TANGELA = 114;
	public const int KANGASKHAN = 115;
	public const int HORSEA = 116;
	public const int SEADRA = 117;
	public const int GOLDEEN = 118;
	public const int SEAKING = 119;
	public const int STARYU = 120;
	public const int STARMIE = 121;
	public const int MRMIME = 122;
	public const int SCYTHER = 123;
	public const int JYNX = 124;
	public const int ELECTABUZZ = 125;
	public const int MAGMAR = 126;
	public const int PINSIR = 127;
	public const int TAUROS = 128;
	public const int MAGIKARP = 129;
	public const int GYARADOS = 130;
	public const int LAPRAS = 131;
	public const int DITTO = 132;
	public const int EEVEE = 133;
	public const int VAPOREON = 134;
	public const int JOLTEON = 135;
	public const int FLAREON = 136;
	public const int PORYGON = 137;
	public const int OMANYTE = 138;
	public const int OMASTAR = 139;
	public const int KABUTO = 140;
	public const int KABUTOPS = 141;
	public const int AERODACTYL = 142;
	public const int SNORLAX = 143;
	public const int ARTICUNO = 144;
	public const int ZAPDOS = 145;
	public const int MOLTRES = 146;
	public const int DRATINI = 147;
	public const int DRAGONAIR = 148;
	public const int DRAGONITE = 149;
	public const int MEWTWO = 150;
	public const int MEW = 151;
	public const int CHIKORITA = 152;
	public const int BAYLEEF = 153;
	public const int MEGANIUM = 154;
	public const int CYNDAQUIL = 155;
	public const int QUILAVA = 156;
	public const int TYPHLOSION = 157;
	public const int TOTODILE = 158;
	public const int CROCONAW = 159;
	public const int FERALIGATR = 160;
	public const int SENTRET = 161;
	public const int FURRET = 162;
	public const int HOOTHOOT = 163;
	public const int NOCTOWL = 164;
	public const int LEDYBA = 165;
	public const int LEDIAN = 166;
	public const int SPINARAK = 167;
	public const int ARIADOS = 168;
	public const int CROBAT = 169;
	public const int CHINCHOU = 170;
	public const int LANTURN = 171;
	public const int PICHU = 172;
	public const int CLEFFA = 173;
	public const int IGGLYBUFF = 174;
	public const int TOGEPI = 175;
	public const int TOGETIC = 176;
	public const int NATU = 177;
	public const int XATU = 178;
	public const int MAREEP = 179;
	public const int FLAAFFY = 180;
	public const int AMPHAROS = 181;
	public const int BELLOSSOM = 182;
	public const int MARILL = 183;
	public const int AZUMARILL = 184;
	public const int SUDOWOODO = 185;
	public const int POLITOED = 186;
	public const int HOPPIP = 187;
	public const int SKIPLOOM = 188;
	public const int JUMPLUFF = 189;
	public const int AIPOM = 190;
	public const int SUNKERN = 191;
	public const int SUNFLORA = 192;
	public const int YANMA = 193;
	public const int WOOPER = 194;
	public const int QUAGSIRE = 195;
	public const int ESPEON = 196;
	public const int UMBREON = 197;
	public const int MURKROW = 198;
	public const int SLOWKING = 199;
	public const int MISDREAVUS = 200;
	public const int UNOWN = 201;
	public const int WOBBUFFET = 202;
	public const int GIRAFARIG = 203;
	public const int PINECO = 204;
	public const int FORRETRESS = 205;
	public const int DUNSPARCE = 206;
	public const int GLIGAR = 207;
	public const int STEELIX = 208;
	public const int SNUBBULL = 209;
	public const int GRANBULL = 210;
	public const int QWILFISH = 211;
	public const int SCIZOR = 212;
	public const int SHUCKLE = 213;
	public const int HERACROSS = 214;
	public const int SNEASEL = 215;
	public const int TEDDIURSA = 216;
	public const int URSARING = 217;
	public const int SLUGMA = 218;
	public const int MAGCARGO = 219;
	public const int SWINUB = 220;
	public const int PILOSWINE = 221;
	public const int CORSOLA = 222;
	public const int REMORAID = 223;
	public const int OCTILLERY = 224;
	public const int DELIBIRD = 225;
	public const int MANTINE = 226;
	public const int SKARMORY = 227;
	public const int HOUNDOUR = 228;
	public const int HOUNDOOM = 229;
	public const int KINGDRA = 230;
	public const int PHANPY = 231;
	public const int DONPHAN = 232;
	public static int PORYGON2 = 233;
	public const int STANTLER = 234;
	public const int SMEARGLE = 235;
	public const int TYROGUE = 236;
	public const int HITMONTOP = 237;
	public const int SMOOCHUM = 238;
	public const int ELEKID = 239;
	public const int MAGBY = 240;
	public const int MILTANK = 241;
	public const int BLISSEY = 242;
	public const int RAIKOU = 243;
	public const int ENTEI = 244;
	public const int SUICUNE = 245;
	public const int LARVITAR = 246;
	public const int PUPITAR = 247;
	public const int TYRANITAR = 248;
	public const int LUGIA = 249;
	public const int HOOH = 250;
	public const int CELEBI = 251;
	public const int TREECKO = 252;
	public const int GROVYLE = 253;
	public const int SCEPTILE = 254;
	public const int TORCHIC = 255;
	public const int COMBUSKEN = 256;
	public const int BLAZIKEN = 257;
	public const int MUDKIP = 258;
	public const int MARSHTOMP = 259;
	public const int SWAMPERT = 260;
	public const int POOCHYENA = 261;
	public const int MIGHTYENA = 262;
	public const int ZIGZAGOON = 263;
	public const int LINOONE = 264;
	public const int WURMPLE = 265;
	public const int SILCOON = 266;
	public const int BEAUTIFLY = 267;
	public const int CASCOON = 268;
	public const int DUSTOX = 269;
	public const int LOTAD = 270;
	public const int LOMBRE = 271;
	public const int LUDICOLO = 272;
	public const int SEEDOT = 273;
	public const int NUZLEAF = 274;
	public const int SHIFTRY = 275;
	public const int TAILLOW = 276;
	public const int SWELLOW = 277;
	public const int WINGULL = 278;
	public const int PELIPPER = 279;
	public const int RALTS = 280;
	public const int KIRLIA = 281;
	public const int GARDEVOIR = 282;
	public const int SURSKIT = 283;
	public const int MASQUERAIN = 284;
	public const int SHROOMISH = 285;
	public const int BRELOOM = 286;
	public const int SLAKOTH = 287;
	public const int VIGOROTH = 288;
	public const int SLAKING = 289;
	public const int NINCADA = 290;
	public const int NINJASK = 291;
	public const int SHEDINJA = 292;
	public const int WHISMUR = 293;
	public const int LOUDRED = 294;
	public const int EXPLOUD = 295;
	public const int MAKUHITA = 296;
	public const int HARIYAMA = 297;
	public const int AZURILL = 298;
	public const int NOSEPASS = 299;
	public const int SKITTY = 300;
	public const int DELCATTY = 301;
	public const int SABLEYE = 302;
	public const int MAWILE = 303;
	public const int ARON = 304;
	public const int LAIRON = 305;
	public const int AGGRON = 306;
	public const int MEDITITE = 307;
	public const int MEDICHAM = 308;
	public const int ELECTRIKE = 309;
	public const int MANECTRIC = 310;
	public const int PLUSLE = 311;
	public const int MINUN = 312;
	public const int VOLBEAT = 313;
	public const int ILLUMISE = 314;
	public const int ROSELIA = 315;
	public const int GULPIN = 316;
	public const int SWALOT = 317;
	public const int CARVANHA = 318;
	public const int SHARPEDO = 319;
	public const int WAILMER = 320;
	public const int WAILORD = 321;
	public const int NUMEL = 322;
	public const int CAMERUPT = 323;
	public const int TORKOAL = 324;
	public const int SPOINK = 325;
	public const int GRUMPIG = 326;
	public const int SPINDA = 327;
	public const int TRAPINCH = 328;
	public const int VIBRAVA = 329;
	public const int FLYGON = 330;
	public const int CACNEA = 331;
	public const int CACTURNE = 332;
	public const int SWABLU = 333;
	public const int ALTARIA = 334;
	public const int ZANGOOSE = 335;
	public const int SEVIPER = 336;
	public const int LUNATONE = 337;
	public const int SOLROCK = 338;
	public const int BARBOACH = 339;
	public const int WHISCASH = 340;
	public const int CORPHISH = 341;
	public const int CRAWDAUNT = 342;
	public const int BALTOY = 343;
	public const int CLAYDOL = 344;
	public const int LILEEP = 345;
	public const int CRADILY = 346;
	public const int ANORITH = 347;
	public const int ARMALDO = 348;
	public const int FEEBAS = 349;
	public const int MILOTIC = 350;
	public const int CASTFORM = 351;
	public const int KECLEON = 352;
	public const int SHUPPET = 353;
	public const int BANETTE = 354;
	public const int DUSKULL = 355;
	public const int DUSCLOPS = 356;
	public const int TROPIUS = 357;
	public const int CHIMECHO = 358;
	public const int ABSOL = 359;
	public const int WYNAUT = 360;
	public const int SNORUNT = 361;
	public const int GLALIE = 362;
	public const int SPHEAL = 363;
	public const int SEALEO = 364;
	public const int WALREIN = 365;
	public const int CLAMPERL = 366;
	public const int HUNTAIL = 367;
	public const int GOREBYSS = 368;
	public const int RELICANTH = 369;
	public const int LUVDISC = 370;
	public const int BAGON = 371;
	public const int SHELGON = 372;
	public const int SALAMENCE = 373;
	public const int BELDUM = 374;
	public const int METANG = 375;
	public const int METAGROSS = 376;
	public const int REGIROCK = 377;
	public const int REGICE = 378;
	public const int REGISTEEL = 379;
	public const int LATIAS = 380;
	public const int LATIOS = 381;
	public const int KYOGRE = 382;
	public const int GROUDON = 383;
	public const int RAYQUAZA = 384;
	public const int JIRACHI = 385;
	public const int DEOXYS = 386;
	public const int TURTWIG = 387;
	public const int GROTLE = 388;
	public const int TORTERRA = 389;
	public const int CHIMCHAR = 390;
	public const int MONFERNO = 391;
	public const int INFERNAPE = 392;
	public const int PIPLUP = 393;
	public const int PRINPLUP = 394;
	public const int EMPOLEON = 395;
	public const int STARLY = 396;
	public const int STARAVIA = 397;
	public const int STARAPTOR = 398;
	public const int BIDOOF = 399;
	public const int BIBAREL = 400;
	public const int KRICKETOT = 401;
	public const int KRICKETUNE = 402;
	public const int SHINX = 403;
	public const int LUXIO = 404;
	public const int LUXRAY = 405;
	public const int BUDEW = 406;
	public const int ROSERADE = 407;
	public const int CRANIDOS = 408;
	public const int RAMPARDOS = 409;
	public const int SHIELDON = 410;
	public const int BASTIODON = 411;
	public const int BURMY = 412;
	public const int WORMADAM = 413;
	public const int MOTHIM = 414;
	public const int COMBEE = 415;
	public const int VESPIQUEN = 416;
	public const int PACHIRISU = 417;
	public const int BUIZEL = 418;
	public const int FLOATZEL = 419;
	public const int CHERUBI = 420;
	public const int CHERRIM = 421;
	public const int SHELLOS = 422;
	public const int GASTRODON = 423;
	public const int AMBIPOM = 424;
	public const int DRIFLOON = 425;
	public const int DRIFBLIM = 426;
	public const int BUNEARY = 427;
	public const int LOPUNNY = 428;
	public const int MISMAGIUS = 429;
	public const int HONCHKROW = 430;
	public const int GLAMEOW = 431;
	public const int PURUGLY = 432;
	public const int CHINGLING = 433;
	public const int STUNKY = 434;
	public const int SKUNTANK = 435;
	public const int BRONZOR = 436;
	public const int BRONZONG = 437;
	public const int BONSLY = 438;
	public const int MIMEJR = 439;
	public const int HAPPINY = 440;
	public const int CHATOT = 441;
	public const int SPIRITOMB = 442;
	public const int GIBLE = 443;
	public const int GABITE = 444;
	public const int GARCHOMP = 445;
	public const int MUNCHLAX = 446;
	public const int RIOLU = 447;
	public const int LUCARIO = 448;
	public const int HIPPOPOTAS = 449;
	public const int HIPPOWDON = 450;
	public const int SKORUPI = 451;
	public const int DRAPION = 452;
	public const int CROAGUNK = 453;
	public const int TOXICROAK = 454;
	public const int CARNIVINE = 455;
	public const int FINNEON = 456;
	public const int LUMINEON = 457;
	public const int MANTYKE = 458;
	public const int SNOVER = 459;
	public const int ABOMASNOW = 460;
	public const int WEAVILE = 461;
	public const int MAGNEZONE = 462;
	public const int LICKILICKY = 463;
	public const int RHYPERIOR = 464;
	public const int TANGROWTH = 465;
	public const int ELECTIVIRE = 466;
	public const int MAGMORTAR = 467;
	public const int TOGEKISS = 468;
	public const int YANMEGA = 469;
	public const int LEAFEON = 470;
	public const int GLACEON = 471;
	public const int GLISCOR = 472;
	public const int MAMOSWINE = 473;
	public const int PORYGONZ = 474;
	public const int GALLADE = 475;
	public const int PROBOPASS = 476;
	public const int DUSKNOIR = 477;
	public const int FROSLASS = 478;
	public const int ROTOM = 479;
	public const int UXIE = 480;
	public const int MESPRIT = 481;
	public const int AZELF = 482;
	public const int DIALGA = 483;
	public const int PALKIA = 484;
	public const int HEATRAN = 485;
	public const int REGIGIGAS = 486;
	public const int GIRATINA = 487;
	public const int CRESSELIA = 488;
	public const int PHIONE = 489;
	public const int MANAPHY = 490;
	public const int DARKRAI = 491;
	public const int SHAYMIN = 492;
	public const int ARCEUS = 493;
	public const int VICTINI = 494;
	public const int SNIVY = 495;
	public const int SERVINE = 496;
	public const int SERPERIOR = 497;
	public const int TEPIG = 498;
	public const int PIGNITE = 499;
	public const int EMBOAR = 500;
	public const int OSHAWOTT = 501;
	public const int DEWOTT = 502;
	public const int SAMUROTT = 503;
	public const int PATRAT = 504;
	public const int WATCHOG = 505;
	public const int LILLIPUP = 506;
	public const int HERDIER = 507;
	public const int STOUTLAND = 508;
	public const int PURRLOIN = 509;
	public const int LIEPARD = 510;
	public const int PANSAGE = 511;
	public const int SIMISAGE = 512;
	public const int PANSEAR = 513;
	public const int SIMISEAR = 514;
	public const int PANPOUR = 515;
	public const int SIMIPOUR = 516;
	public const int MUNNA = 517;
	public const int MUSHARNA = 518;
	public const int PIDOVE = 519;
	public const int TRANQUILL = 520;
	public const int UNFEZANT = 521;
	public const int BLITZLE = 522;
	public const int ZEBSTRIKA = 523;
	public const int ROGGENROLA = 524;
	public const int BOLDORE = 525;
	public const int GIGALITH = 526;
	public const int WOOBAT = 527;
	public const int SWOOBAT = 528;
	public const int DRILBUR = 529;
	public const int EXCADRILL = 530;
	public const int AUDINO = 531;
	public const int TIMBURR = 532;
	public const int GURDURR = 533;
	public const int CONKELDURR = 534;
	public const int TYMPOLE = 535;
	public const int PALPITOAD = 536;
	public const int SEISMITOAD = 537;
	public const int THROH = 538;
	public const int SAWK = 539;
	public const int SEWADDLE = 540;
	public const int SWADLOON = 541;
	public const int LEAVANNY = 542;
	public const int VENIPEDE = 543;
	public const int WHIRLIPEDE = 544;
	public const int SCOLIPEDE = 545;
	public const int COTTONEE = 546;
	public const int WHIMSICOTT = 547;
	public const int PETILIL = 548;
	public const int LILLIGANT = 549;
	public const int BASCULIN = 550;
	public const int SANDILE = 551;
	public const int KROKOROK = 552;
	public const int KROOKODILE = 553;
	public const int DARUMAKA = 554;
	public const int DARMANITAN = 555;
	public const int MARACTUS = 556;
	public const int DWEBBLE = 557;
	public const int CRUSTLE = 558;
	public const int SCRAGGY = 559;
	public const int SCRAFTY = 560;
	public const int SIGILYPH = 561;
	public const int YAMASK = 562;
	public const int COFAGRIGUS = 563;
	public const int TIRTOUGA = 564;
	public const int CARRACOSTA = 565;
	public const int ARCHEN = 566;
	public const int ARCHEOPS = 567;
	public const int TRUBBISH = 568;
	public const int GARBODOR = 569;
	public const int ZORUA = 570;
	public const int ZOROARK = 571;
	public const int MINCCINO = 572;
	public const int CINCCINO = 573;
	public const int GOTHITA = 574;
	public const int GOTHORITA = 575;
	public const int GOTHITELLE = 576;
	public const int SOLOSIS = 577;
	public const int DUOSION = 578;
	public const int REUNICLUS = 579;
	public const int DUCKLETT = 580;
	public const int SWANNA = 581;
	public const int VANILLITE = 582;
	public const int VANILLISH = 583;
	public const int VANILLUXE = 584;
	public const int DEERLING = 585;
	public const int SAWSBUCK = 586;
	public const int EMOLGA = 587;
	public const int KARRABLAST = 588;
	public const int ESCAVALIER = 589;
	public const int FOONGUS = 590;
	public const int AMOONGUSS = 591;
	public const int FRILLISH = 592;
	public const int JELLICENT = 593;
	public const int ALOMOMOLA = 594;
	public const int JOLTIK = 595;
	public const int GALVANTULA = 596;
	public const int FERROSEED = 597;
	public const int FERROTHORN = 598;
	public const int KLINK = 599;
	public const int KLANG = 600;
	public const int KLINKLANG = 601;
	public const int TYNAMO = 602;
	public const int EELEKTRIK = 603;
	public const int EELEKTROSS = 604;
	public const int ELGYEM = 605;
	public const int BEHEEYEM = 606;
	public const int LITWICK = 607;
	public const int LAMPENT = 608;
	public const int CHANDELURE = 609;
	public const int AXEW = 610;
	public const int FRAXURE = 611;
	public const int HAXORUS = 612;
	public const int CUBCHOO = 613;
	public const int BEARTIC = 614;
	public const int CRYOGONAL = 615;
	public const int SHELMET = 616;
	public const int ACCELGOR = 617;
	public const int STUNFISK = 618;
	public const int MIENFOO = 619;
	public const int MIENSHAO = 620;
	public const int DRUDDIGON = 621;
	public const int GOLETT = 622;
	public const int GOLURK = 623;
	public const int PAWNIARD = 624;
	public const int BISHARP = 625;
	public const int BOUFFALANT = 626;
	public const int RUFFLET = 627;
	public const int BRAVIARY = 628;
	public const int VULLABY = 629;
	public const int MANDIBUZZ = 630;
	public const int HEATMOR = 631;
	public const int DURANT = 632;
	public const int DEINO = 633;
	public const int ZWEILOUS = 634;
	public const int HYDREIGON = 635;
	public const int LARVESTA = 636;
	public const int VOLCARONA = 637;
	public const int COBALION = 638;
	public const int TERRAKION = 639;
	public const int VIRIZION = 640;
	public const int TORNADUS = 641;
	public const int THUNDURUS = 642;
	public const int RESHIRAM = 643;
	public const int ZEKROM = 644;
	public const int LANDORUS = 645;
	public const int KYUREM = 646;
	public const int KELDEO = 647;
	public const int MELOETTA = 648;
	public const int GENESECT = 649;
	public const int AEGISLASH = 650;
	public const int XERNEAS = 651;
	public const int HOOPA = 652;
	public const int SCATTERBUG = 653;
	public const int SPEWPA = 654;
	public const int VIVILLON = 655;
	public const int FLABEBE = 656;
	public const int FLOETTE = 657;
	public const int FLORGES = 658;
	public const int FURFROU = 659;
	public const int PUMPKABOO = 660;
	public const int GOURGEIST = 661;

	public static string[] speciesNames = new string[661]{"BULBASAUR","IVYSAUR","VENUSAUR","CHARMANDER","CHARMELEON","CHARIZARD","SQUIRTLE","WARTORTLE","BLASTOISE","CATERPIE","METAPOD","BUTTERFREE","WEEDLE","KAKUNA","BEEDRILL","PIDGEY","PIDGEOTTO","PIDGEOT","RATTATA","RATICATE","SPEAROW","FEAROW","EKANS","ARBOK","PIKACHU","RAICHU","SANDSHREW","SANDSLASH","NIDORANfE","NIDORINA","NIDOQUEEN","NIDORANmA","NIDORINO","NIDOKING","CLEFAIRY","CLEFABLE","VULPIX","NINETALES","JIGGLYPUFF","WIGGLYTUFF","ZUBAT","GOLBAT","ODDISH","GLOOM","VILEPLUME","PARAS","PARASECT","VENONAT","VENOMOTH","DIGLETT","DUGTRIO","MEOWTH","PERSIAN","PSYDUCK","GOLDUCK","MANKEY","PRIMEAPE","GROWLITHE","ARCANINE","POLIWAG","POLIWHIRL","POLIWRATH","ABRA","KADABRA","ALAKAZAM","MACHOP","MACHOKE","MACHAMP","BELLSPROUT","WEEPINBELL","VICTREEBEL","TENTACOOL","TENTACRUEL","GEODUDE","GRAVELER","GOLEM","PONYTA","RAPIDASH","SLOWPOKE","SLOWBRO","MAGNEMITE","MAGNETON","FARFETCHD","DODUO","DODRIO","SEEL","DEWGONG","GRIMER","MUK","SHELLDER","CLOYSTER","GASTLY","HAUNTER","GENGAR","ONIX","DROWZEE","HYPNO","KRABBY","KINGLER","VOLTORB","ELECTRODE","EXEGGCUTE","EXEGGUTOR","CUBONE","MAROWAK","HITMONLEE","HITMONCHAN","LICKITUNG","KOFFING","WEEZING","RHYHORN","RHYDON","CHANSEY","TANGELA","KANGASKHAN","HORSEA","SEADRA","GOLDEEN","SEAKING","STARYU","STARMIE","MRMIME","SCYTHER","JYNX","ELECTABUZZ","MAGMAR","PINSIR","TAUROS","MAGIKARP","GYARADOS","LAPRAS","DITTO","EEVEE","VAPOREON","JOLTEON","FLAREON","PORYGON","OMANYTE","OMASTAR","KABUTO","KABUTOPS","AERODACTYL","SNORLAX","ARTICUNO","ZAPDOS","MOLTRES","DRATINI","DRAGONAIR","DRAGONITE","MEWTWO","MEW","CHIKORITA","BAYLEEF","MEGANIUM","CYNDAQUIL","QUILAVA","TYPHLOSION","TOTODILE","CROCONAW","FERALIGATR","SENTRET","FURRET","HOOTHOOT","NOCTOWL","LEDYBA","LEDIAN","SPINARAK","ARIADOS","CROBAT","CHINCHOU","LANTURN","PICHU","CLEFFA","IGGLYBUFF","TOGEPI","TOGETIC","NATU","XATU","MAREEP","FLAAFFY","AMPHAROS","BELLOSSOM","MARILL","AZUMARILL","SUDOWOODO","POLITOED","HOPPIP","SKIPLOOM","JUMPLUFF","AIPOM","SUNKERN","SUNFLORA","YANMA","WOOPER","QUAGSIRE","ESPEON","UMBREON","MURKROW","SLOWKING","MISDREAVUS","UNOWN","WOBBUFFET","GIRAFARIG","PINECO","FORRETRESS","DUNSPARCE","GLIGAR","STEELIX","SNUBBULL","GRANBULL","QWILFISH","SCIZOR","SHUCKLE","HERACROSS","SNEASEL","TEDDIURSA","URSARING","SLUGMA","MAGCARGO","SWINUB","PILOSWINE","CORSOLA","REMORAID","OCTILLERY","DELIBIRD","MANTINE","SKARMORY","HOUNDOUR","HOUNDOOM","KINGDRA","PHANPY","DONPHAN"," PORYGON2","STANTLER","SMEARGLE","TYROGUE","HITMONTOP","SMOOCHUM","ELEKID","MAGBY","MILTANK","BLISSEY","RAIKOU","ENTEI","SUICUNE","LARVITAR","PUPITAR","TYRANITAR","LUGIA","HOOH","CELEBI","TREECKO","GROVYLE","SCEPTILE","TORCHIC","COMBUSKEN","BLAZIKEN","MUDKIP","MARSHTOMP","SWAMPERT","POOCHYENA","MIGHTYENA","ZIGZAGOON","LINOONE","WURMPLE","SILCOON","BEAUTIFLY","CASCOON","DUSTOX","LOTAD","LOMBRE","LUDICOLO","SEEDOT","NUZLEAF","SHIFTRY","TAILLOW","SWELLOW","WINGULL","PELIPPER","RALTS","KIRLIA","GARDEVOIR","SURSKIT","MASQUERAIN","SHROOMISH","BRELOOM","SLAKOTH","VIGOROTH","SLAKING","NINCADA","NINJASK","SHEDINJA","WHISMUR","LOUDRED","EXPLOUD","MAKUHITA","HARIYAMA","AZURILL","NOSEPASS","SKITTY","DELCATTY","SABLEYE","MAWILE","ARON","LAIRON","AGGRON","MEDITITE","MEDICHAM","ELECTRIKE","MANECTRIC","PLUSLE","MINUN","VOLBEAT","ILLUMISE","ROSELIA","GULPIN","SWALOT","CARVANHA","SHARPEDO","WAILMER","WAILORD","NUMEL","CAMERUPT","TORKOAL","SPOINK","GRUMPIG","SPINDA","TRAPINCH","VIBRAVA","FLYGON","CACNEA","CACTURNE","SWABLU","ALTARIA","ZANGOOSE","SEVIPER","LUNATONE","SOLROCK","BARBOACH","WHISCASH","CORPHISH","CRAWDAUNT","BALTOY","CLAYDOL","LILEEP","CRADILY","ANORITH","ARMALDO","FEEBAS","MILOTIC","CASTFORM","KECLEON","SHUPPET","BANETTE","DUSKULL","DUSCLOPS","TROPIUS","CHIMECHO","ABSOL","WYNAUT","SNORUNT","GLALIE","SPHEAL","SEALEO","WALREIN","CLAMPERL","HUNTAIL","GOREBYSS","RELICANTH","LUVDISC","BAGON","SHELGON","SALAMENCE","BELDUM","METANG","METAGROSS","REGIROCK","REGICE","REGISTEEL","LATIAS","LATIOS","KYOGRE","GROUDON","RAYQUAZA","JIRACHI","DEOXYS","TURTWIG","GROTLE","TORTERRA","CHIMCHAR","MONFERNO","INFERNAPE","PIPLUP","PRINPLUP","EMPOLEON","STARLY","STARAVIA","STARAPTOR","BIDOOF","BIBAREL","KRICKETOT","KRICKETUNE","SHINX","LUXIO","LUXRAY","BUDEW","ROSERADE","CRANIDOS","RAMPARDOS","SHIELDON","BASTIODON","BURMY","WORMADAM","MOTHIM","COMBEE","VESPIQUEN","PACHIRISU","BUIZEL","FLOATZEL","CHERUBI","CHERRIM","SHELLOS","GASTRODON","AMBIPOM","DRIFLOON","DRIFBLIM","BUNEARY","LOPUNNY","MISMAGIUS","HONCHKROW","GLAMEOW","PURUGLY","CHINGLING","STUNKY","SKUNTANK","BRONZOR","BRONZONG","BONSLY","MIMEJR","HAPPINY","CHATOT","SPIRITOMB","GIBLE","GABITE","GARCHOMP","MUNCHLAX","RIOLU","LUCARIO","HIPPOPOTAS","HIPPOWDON","SKORUPI","DRAPION","CROAGUNK","TOXICROAK","CARNIVINE","FINNEON","LUMINEON","MANTYKE","SNOVER","ABOMASNOW","WEAVILE","MAGNEZONE","LICKILICKY","RHYPERIOR","TANGROWTH","ELECTIVIRE","MAGMORTAR","TOGEKISS","YANMEGA","LEAFEON","GLACEON","GLISCOR","MAMOSWINE","PORYGONZ","GALLADE","PROBOPASS","DUSKNOIR","FROSLASS","ROTOM","UXIE","MESPRIT","AZELF","DIALGA","PALKIA","HEATRAN","REGIGIGAS","GIRATINA","CRESSELIA","PHIONE","MANAPHY","DARKRAI","SHAYMIN","ARCEUS","VICTINI","SNIVY","SERVINE","SERPERIOR","TEPIG","PIGNITE","EMBOAR","OSHAWOTT","DEWOTT","SAMUROTT","PATRAT","WATCHOG","LILLIPUP","HERDIER","STOUTLAND","PURRLOIN","LIEPARD","PANSAGE","SIMISAGE","PANSEAR","SIMISEAR","PANPOUR","SIMIPOUR","MUNNA","MUSHARNA","PIDOVE","TRANQUILL","UNFEZANT","BLITZLE","ZEBSTRIKA","ROGGENROLA","BOLDORE","GIGALITH","WOOBAT","SWOOBAT","DRILBUR","EXCADRILL","AUDINO","TIMBURR","GURDURR","CONKELDURR","TYMPOLE","PALPITOAD","SEISMITOAD","THROH","SAWK","SEWADDLE","SWADLOON","LEAVANNY","VENIPEDE","WHIRLIPEDE","SCOLIPEDE","COTTONEE","WHIMSICOTT","PETILIL","LILLIGANT","BASCULIN","SANDILE","KROKOROK","KROOKODILE","DARUMAKA","DARMANITAN","MARACTUS","DWEBBLE","CRUSTLE","SCRAGGY","SCRAFTY","SIGILYPH","YAMASK","COFAGRIGUS","TIRTOUGA","CARRACOSTA","ARCHEN","ARCHEOPS","TRUBBISH","GARBODOR","ZORUA","ZOROARK","MINCCINO","CINCCINO","GOTHITA","GOTHORITA","GOTHITELLE","SOLOSIS","DUOSION","REUNICLUS","DUCKLETT","SWANNA","VANILLITE","VANILLISH","VANILLUXE","DEERLING","SAWSBUCK","EMOLGA","KARRABLAST","ESCAVALIER","FOONGUS","AMOONGUSS","FRILLISH","JELLICENT","ALOMOMOLA","JOLTIK","GALVANTULA","FERROSEED","FERROTHORN","KLINK","KLANG","KLINKLANG","TYNAMO","EELEKTRIK","EELEKTROSS","ELGYEM","BEHEEYEM","LITWICK","LAMPENT","CHANDELURE","AXEW","FRAXURE","HAXORUS","CUBCHOO","BEARTIC","CRYOGONAL","SHELMET","ACCELGOR","STUNFISK","MIENFOO","MIENSHAO","DRUDDIGON","GOLETT","GOLURK","PAWNIARD","BISHARP","BOUFFALANT","RUFFLET","BRAVIARY","VULLABY","MANDIBUZZ","HEATMOR","DURANT","DEINO","ZWEILOUS","HYDREIGON","LARVESTA","VOLCARONA","COBALION","TERRAKION","VIRIZION","TORNADUS","THUNDURUS","RESHIRAM","ZEKROM","LANDORUS","KYUREM","KELDEO","MELOETTA","GENESECT","AEGISLASH","XERNEAS","HOOPA","SCATTERBUG","SPEWPA","VIVILLON","FLABEBE","FLOETTE","FLORGES","FURFROU","PUMPKABOO","GOURGEIST"};

	public static int GetValueFromName(string type) {
		for (int i=0; i<speciesNames.Length; i++) {
			if (speciesNames[i] == type) {
				return i+1;
			}
		}
		return -1;
	}

	public static int MaxValue() {
		return 802;
	}

	private const string speciesPath = "Assets/lib/data/pokemon.json";
	private const string formsPath = "Assets/lib/data/forms.json";

	public static InternalSpecies GetSpecies(int id) {
		string json = System.IO.File.ReadAllText(speciesPath);
		InternalSpecies[] species = JsonHelper.FromJson<InternalSpecies>(json);
		for (int i = 0; i < species.Length; i++) {
			if (species[i].Number == id) {
				return species[i];
			}
		}
		return null;
	}

	public static InternalForm GetForm(string species, int form) {
		string json = System.IO.File.ReadAllText(formsPath);
		InternalForm[] forms = JsonHelper.FromJson<InternalForm>(json);
		for (int i = 0; i < forms.Length; i++) {
			if (forms[i].InternalName == species + "-" + form) {
				return forms[i];
			}
		}
		return null;
	}

	public static string GetName(int id) {
		InternalSpecies sp = GetSpecies(id);
		if (sp == null) {
			return "";
		}
		return sp.Name;
	}

	[Serializable]
	public class InternalSpecies {
		public string[] Abilities;
		public int BaseEXP;
		public BStats BaseStats;
		public int BattlerAltitude;
		public int BattlerEnemyY;
		public int BattlerPlayerY;
		public string Color;
		public string[] Compatibility;
		public BStats EffortPoints;
		public string[] EggMoves;
		public Evolution[] Evolutions;
		public string FormName;
		public string GenderRate;
		public string GrowthRate;
		public string Habitat;
		public int Happiness;
		public float Height;
		public string HiddenAbility;
		public string Incense;
		public string InternalName;
		public string Kind;
		public LevMove[] Moves;
		public string Name;
		public int Number;
		public string Pokedex;
		public int Rareness;
		public int[] RegionalNumbers;
		public int Shape;
		public int StepsToHatch;
		public string Type1;
		public string Type2;
		public float Weight;
		public string[] WildItemCommon;
		public string[] WildItemUncommon;
		public string[] WildItemRare;
	}
	[Serializable]
	public class InternalForm {
		public string[] Abilities;
		public int BaseEXP;
		public BStats BaseStats;
		public int BattlerAltitude;
		public int BattlerEnemyY;
		public int BattlerPlayerY;
		public string Color;
		public BStats EffortPoints;
		public string[] EggMoves;
		public Evolution[] Evolutions;
		public string FormName;
		public string Habitat;
		public int Happiness;
		public float Height;
		public string HiddenAbility;
		public string InternalName;
		public string Kind;
		public int MegaMessage;
		public string MegaMove;
		public string MegaStone;
		public LevMove[] Moves;
		public int Number;
		public string Pokedex;
		public int Rareness;
		public int Shape;
		public int StepsToHatch;
		public string Type1;
		public string Type2;
		public int UnmegaForm;
		public float Weight;
		public string[] WildItemCommon;
		public string[] WildItemUncommon;
		public string[] WildItemRare;
	}
	[Serializable]
	public class BStats {
		public int Attack;
		public int Defense;
		public int HP;
		public int SpecialAttack;
		public int SpecialDefense;
		public int Speed;
	}
	[Serializable]
	public class Evolution {
		public string Method;
		public string Pokemon;
		public string Value;
	}
	[Serializable]
	public class LevMove {
		public int Level;
		public string Move;
	}
}